# Generated by Django 5.2 on 2025-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
