# Generated by Django 5.2 on 2025-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0002_remove_customuser_secret_key_customuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
